version: '3.9'
services:
  database:
    image: mongo:5
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    restart: always
    ports:
      - "${DATABASE_PORT}:27017"